#!/usr/bin/env python
import os
import subprocess

try:
    from setuptools import setup
except:
    from ez_setup import use_setuptools
    use_setuptools()

extra = {}

# Fetch version from git tags, and write to version.py.
# Also, when git is not available (PyPi package), use stored version.py.
version_py = os.path.join(os.path.dirname(__file__), 'evconverter/version.py')

try:
    version_git = subprocess.check_output(["git", "describe"]).rstrip()
except:
    with open(version_py, 'r') as fh:
        version_git = open(version_py).read().strip().split('=')[-1].replace('"', '')

version_msg = "# Do not edit this file, pipeline versioning is governed by git tags"
with open(version_py, 'w') as fh:
    fh.write(version_msg + os.linesep + "__version__ = '" + version_git + "'")


setup(
    name="evconverter",
    packages=['evconverter'],
    include_package_data=True,
    version="{ver}".format(ver=version_git),
    description="Converter for Bookkeeping data exported from a PMS",
    author="Markus Mattes",
    author_email="mmattes87@gmail.com",
    url="https://github.com/mmattes/easyVET-to-Exact-Converter",
    license="MIT license",
    keywords="easyVET exact bookkeeping",
    classifiers=[
        "License :: OSI Approved :: MIT License",
        "Environment :: Console",
        "Intended Audience :: Developers",
        "Development Status :: 5 - Production/Stable",
        "Programming Language :: Python",
        "Programming Language :: Python :: 2.6",
        "Programming Language :: Python :: 2.7",
        "Programming Language :: Python :: 3.0",
        "Programming Language :: Python :: 3.2",
        "Programming Language :: Python :: 3.3",
        "Programming Language :: Python :: 3.4",
        "Operating System :: OS Independent",
        "Topic :: Office/Business :: Financial :: Accounting",
        "Topic :: Text Processing"
    ],
    long_description="""
    evconverter is a small script tools which helps to convert data created from a veterinary
    practice managment solution called easyVET to a bookkeeping solution called Exact. The
    exported data from the PMS (www.easyvet.eu, www.vetz.de) is existing in Text format with Tabs
    as seperator and will be converterd to the XML format of Exact (www.exact.nl)
    """,
    **extra
)
